version: '3.8'

services:
  backend:
    build: .
    container_name: job-portal-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
